export const PackageStatus = {
  TO_BE_PICKED_UP: "TO_BE_PICKED_UP",
  PICKED_UP: "PICKED_UP",
  ADDED_TO_BAG: "ADDED_TO_BAG",
  LOADED_ON_TRUCK: "LOADED_ON_TRUCK",
  EN_ROUTE: "EN_ROUTE",
  ARRIVED_AT_REGION: "ARRIVED_AT_REGION",
  SCHEDULED_FOR_DELIVERY: "SCHEDULED_FOR_DELIVERY",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELAYED: "DELAYED",
  DELIVERED: "DELIVERED",
} as const;

export type PackageStatus = (typeof PackageStatus)[keyof typeof PackageStatus];
